import { useState, useEffect } from 'react'
import { supabase } from '../supabase.js'
import OrderButton from '../components/OrderButton.jsx'
import AdminOrders from '../components/AdminOrders.jsx'
import './ProductsPage.css'
const CATS = ['الكل', 'جوالات', 'سيارات', 'أثاث', 'إلكترونيات', 'ملابس', 'أخرى']
const CITIES = ['الكل', 'المكلا', 'الشحر', 'سيئون', 'غيل باوزير']
export default function ProductsPage({ isAdmin, dark }) {
    const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [cat, setCat] = useState('الكل'); const [city, setCity] = useState('الكل'); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ title: '', category: 'جوالات', city: 'المكلا', price: '', whatsapp: '', description: '' })
    const fetchData = async () => { const { data } = await supabase.from('products').select('*').order('created_at', { ascending: false }); setItems(data || []) }
    useEffect(() => { fetchData() }, [])
    const handleAdd = async (e) => { e.preventDefault(); const { error } = await supabase.from('products').insert([form]); if (error) alert(error.message); else { setShowForm(false); fetchData(); setForm({ title: '', category: 'جوالات', city: 'المكلا', price: '', whatsapp: '', description: '' }) } }
    const handleDelete = async (id) => { if (!confirm('تحذف؟')) return; await supabase.from('products').delete().eq('id', id); fetchData() }
    const filtered = items.filter(i => i.title.toLowerCase().includes(search.toLowerCase()) && (cat === 'الكل' || i.category === cat) && (city === 'الكل' || i.city === city))
    return (<div className="page" style={{ background: dark? '#121212' : 'transparent', padding: 16 }}><div style={{ maxWidth: 1100, margin: '0 auto' }}>
        <div className="header"><div className="header-left"><div className="header-icon" style={{ background: '#2563eb' }}>🛒</div><div><div style={{ fontWeight: 900, color: dark? 'white' : '#111' }}>سوق حضرموت {isAdmin && '👑'}</div><div style={{ fontSize: 12, color: '#888' }}>بيع واشتري</div></div></div><div style={{ display: 'flex', gap: 8 }}>{isAdmin && <AdminOrders service_type="products" dark={dark} />}<button onClick={() => setShowForm(!showForm)} style={{ background: '#2563eb', color: 'white', padding: '8px 16px', borderRadius: 999, border: 'none', fontWeight: 'bold' }}>اعرض منتجك</button></div></div>
        <div className="filter-bar"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث جوال، سيارة..." /><div className="filter-btns">{CATS.map(c => <button key={c} onClick={() => setCat(c)} className={cat === c? 'active' : ''} style={cat === c? { background: '#2563eb', color: 'white', borderColor: '#2563eb' } : {}}>{c}</button>)}</div></div>
        {showForm && <form onSubmit={handleAdd} className="form-box"><input placeholder="ماذا تبيع؟" value={form.title} onChange={e => setForm({...form, title: e.target.value })} required /><select value={form.category} onChange={e => setForm({...form, category: e.target.value })}>{CATS.slice(1).map(t => <option key={t}>{t}</option>)}</select><select value={form.city} onChange={e => setForm({...form, city: e.target.value })}>{CITIES.slice(1).map(c => <option key={c}>{c}</option>)}</select><input placeholder="السعر" value={form.price} onChange={e => setForm({...form, price: e.target.value })} required /><input placeholder="واتساب" value={form.whatsapp} onChange={e => setForm({...form, whatsapp: e.target.value })} required /><textarea placeholder="وصف السلعة" value={form.description} onChange={e => setForm({...form, description: e.target.value })}></textarea><button className="submit" style={{ background: '#2563eb' }}>نشر</button></form>}
        <div className="grid-4">{filtered.map(c => <div key={c.id} className="card" style={{ background: dark? '#1e1e1e' : 'white', border: dark? '1px solid #333' : '1px solid #eee' }}>{isAdmin && <button onClick={() => handleDelete(c.id)} className="delete-btn">✕</button>}<div className="product-image">📦</div><span className="badge">{c.category} • {c.city}</span><div style={{ fontWeight: 'bold', fontSize: 14, marginTop: 8, color: dark? 'white' : '#111' }}>{c.title}</div><div className="price" style={{ color: '#2563eb' }}>{c.price}</div><div style={{ display: 'flex', gap: 6, marginTop: 10 }}><OrderButton item={c} service_type="products" /></div></div>)}</div>
    </div></div>)
}